import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "./Components/Banner";
import CoffeeShopSelector from "./Components/CoffeeShopSelector";

const coffeeShops = [
  {
    title: "Coffee-Shop 1",
    id: 1,
  },
  {
    title: "Coffee-Shop 2",
    id: 2,
  },
  {
    title: "Coffee-Shop 3",
    id: 3,
  },
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        {coffeeShops.map((shop) => {
          return (
            <CoffeeShopSelector key={shop.id} title={shop.title} id={shop.id} />
          );
        })}
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
