import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "./Components/Banner";
import Link from "next/link";

export default function Home() {
  const id = 1;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <Link href={`/coffee-shop/${id}`}>
          <a>Take me to {id}</a>
        </Link>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
